### ISSUE TITLE
PyPi?

### ISSUE THREAD

**Issue by yjftsjthsd-g** [sgnn7/ez_gpg#2]
It would be nice if you could put this on [PyPi](https://pypi.python.org/pypi), because then it could be installed with pip. Obviously fpm works well, but most python users will already have pip ready to go and this would lower the barrier to entry even further. It _should_ be easy (I think) since you've already got it working with setuputils.

**Comment by sgnn7** [comment]
@yjftsjthsd-g Yup, I'll be doing that in the next couple of days - I was going to do it today but `fpm`ification took too long.

**Comment by sgnn7** [comment]
@yjftsjthsd-g: https://pypi.python.org/pypi/ezgpg/0.1
